"""Initial Migration.

Revision ID: c6989579b221
Revises: 
Create Date: 2020-12-11 16:16:08.990869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6989579b221'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('change_color', sa.String(length=10), nullable=True))
    op.alter_column('device', 'brightness',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('device', 'color',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('device', 'on_off',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'on_off',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('device', 'color',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('device', 'brightness',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('device', 'change_color')
    # ### end Alembic commands ###
